import images from "../../assets/products/images";

const ProductList = [
    // Mens Shirts
    {
        name: "Men's ULURU White Tee",
        gender: "men",
        type: "shirt",
        price: "19.99",
        img: images.men.shirt[0],
    },
    {
        name: "Men's White Long Sleeve",
        gender: "men",
        type: "shirt",
        price: "29.49",
        img: images.men.shirt[1]
    },
    {
        name: "Men's Milk Jug White Tee",
        gender: "men",
        type: "shirt",
        price: "23.99",
        img: images.men.shirt[2]
    },
    {
        name: "Men's Floral Button Up Tee",
        gender: "men",
        type: "shirt",
        price: "45.99",
        img: images.men.shirt[3]
    },
    {
        name: "Men's Taco Black Tee",
        gender: "men",
        type: "shirt",
        price: "22.99",
        img: images.men.shirt[4],
    },
    {
        name: "Men's Blue Gradient Tee",
        gender: "men",
        type: "shirt",
        price: "25.99",
        img: images.men.shirt[5],
    },
    {
        name: "Men's Lumberjack Flannel Long Sleeve",
        gender: "men",
        type: "shirt",
        price: "42.99",
        img: images.men.shirt[6],
    },
    {
        name: "Men's Turquoise Formal Tee",
        gender: "men",
        type: "shirt",
        price: "38.99",
        img: images.men.shirt[7],
    },
    {
        name: "Men's Hello Kitty Black Tee",
        gender: "men",
        type: "shirt",
        price: "34.99",
        img: images.men.shirt[8],
    },
    // Mens Pants
    {
        name: "Men's Black Sleek-Fit Shorts",
        gender: "men",
        type: "pants",
        price: "29.99",
        img: images.men.pants[0],
    },
    {
        name: "Men's Black Jeans",
        gender: "men",
        type: "pants",
        price: "59.99",
        img: images.men.pants[1]
    },
    {
        name: "Men's Red Pants",
        gender: "men",
        type: "pants",
        price: "74.99",
        img: images.men.pants[2]
    },
    {
        name: "Men's Camo Cargo Pants",
        gender: "men",
        type: "pants",
        price: "55.99",
        img: images.men.pants[3]
    },
    {
        name: "Men's Green Track Pants",
        gender: "men",
        type: "pants",
        price: "49.99",
        img: images.men.pants[4],
    },
    {
        name: "Men's Palm Tree Shorts",
        gender: "men",
        type: "pants",
        price: "35.99",
        img: images.men.pants[5],
    },
    {
        name: "Men's Hands Black Shorts",
        gender: "men",
        type: "pants",
        price: "32.99",
        img: images.men.pants[6],
    },
    {
        name: "Men's WNDR Bones Light Grey Shorts",
        gender: "men",
        type: "pants",
        price: "24.99",
        img: images.men.pants[7],
    },
    {
        name: "Men's Orange Pants",
        gender: "men",
        type: "pants",
        price: "49.99",
        img: images.men.pants[8],
    },
    // Mens Jackets
    {
        name: "Men's PNUMA Outdoor Jacket",
        gender: "men",
        type: "jacket",
        price: "79.59",
        img: images.men.jacket[0],
    },
    {
        name: "Men's Red HH Outdoor Jacket",
        gender: "men",
        type: "jacket",
        price: "73.99",
        img: images.men.jacket[1]
    },
    {
        name: "Men's Black Leather Jacket",
        gender: "men",
        type: "jacket",
        price: "83.79",
        img: images.men.jacket[2],
    },
    {
        name: "Men's Yellow Button Jacket",
        gender: "men",
        type: "jacket",
        price: "80.99",
        img: images.men.jacket[3],
    },
    {
        name: "Men's Orange & Brown Jacket",
        gender: "men",
        type: "jacket",
        price: "67.29",
        img: images.men.jacket[4],
    },
    {
        name: "Men's Yellow Strap Jacket",
        gender: "men",
        type: "jacket",
        price: "97.99",
        img: images.men.jacket[5],
    },
    {
        name: "Men's Blue Jacket",
        gender: "men",
        type: "jacket",
        price: "73.99",
        img: images.men.jacket[6],
    },
    {
        name: "Men's Orange Rain Jacket",
        gender: "men",
        type: "jacket",
        price: "63.99",
        img: images.men.jacket[7],
    },
    {
        name: "Men's Premium Leather Jacket",
        gender: "men",
        type: "jacket",
        price: "104.99",
        img: images.men.jacket[8],
    },
    // Mens Sweaters
    {
        name: "Men's Japanese Character Hoodie",
        gender: "men",
        type: "sweater",
        price: "66.99",
        img: images.men.sweater[0],
    },
    {
        name: "Men's SUPREME Yellow Hoodie",
        gender: "men",
        type: "sweater",
        price: "259.99",
        img: images.men.sweater[1],
    },
    {
        name: "Men's TMNT Black Hoodie",
        gender: "men",
        type: "sweater",
        price: "79.99",
        img: images.men.sweater[2],
    },
    {
        name: "Men's POKEMON Blue Rayquaza Hoodie",
        gender: "men",
        type: "sweater",
        price: "79.99",
        img: images.men.sweater[3]
    },
    {
        name: "Men's Rolling Stone Tie-Dye Hoodie",
        gender: "men",
        type: "sweater",
        price: "85.99",
        img: images.men.sweater[4],
    },
    {
        name: "Men's SUPREME Diagonal Blue Hoodie",
        gender: "men",
        type: "sweater",
        price: "149.99",
        img: images.men.sweater[5],
    },
    {
        name: "Men's Pink Planet Hoodie",
        gender: "men",
        type: "sweater",
        price: "69.79",
        img: images.men.sweater[6],
    },
    {
        name: "Men's Blue Friend Hoodie",
        gender: "men",
        type: "sweater",
        price: "64.99",
        img: images.men.sweater[7],
    },
    {
        name: "Men's Peace Black Hoodie",
        gender: "men",
        type: "sweater",
        price: "75.99",
        img: images.men.sweater[8],
    },
    // Womens Shirts
    {
        name: "Women's Blonde Hair White Tee",
        gender: "women",
        type: "shirt",
        price: "23.99",
        img: images.women.shirt[0],
    },
    {
        name: "Women's Life Is Good Bee Pink Tee",
        gender: "women",
        type: "shirt",
        price: "19.99",
        img: images.women.shirt[1],
    },
    {
        name: "Women's Surfing Pepper Pink Tee",
        gender: "women",
        type: "shirt",
        price: "24.99",
        img: images.women.shirt[2],
    },
    {
        name: "Women's Yosemite Sam White Tee",
        gender: "women",
        type: "shirt",
        price: "19.99",
        img: images.women.shirt[3],
    },
    {
        name: "Women's Hawaiian Crop Top",
        gender: "women",
        type: "shirt",
        price: "22.99",
        img: images.women.shirt[4],
    },
    {
        name: "Women's BANYAN Black Tee",
        gender: "women",
        type: "shirt",
        price: "20.99",
        img: images.women.shirt[5],
    },
    {
        name: "Women's 1963 Iota Yellow Tee",
        gender: "women",
        type: "shirt",
        price: "27.99",
        img: images.women.shirt[6],
    },
    {
        name: "Women's Hamster Love Navy Tank Top",
        gender: "women",
        type: "shirt",
        price: "17.99",
        img: images.women.shirt[7],
    },
    {
        name: "Women's Life Is Good Bath Navy Tee",
        gender: "women",
        type: "shirt",
        price: "23.99",
        img: images.women.shirt[8],
    },
    // Womens Dresses
    {
        name: "Women's Yellow Summer Dress",
        gender: "women",
        type: "dress",
        price: "32.59",
        img: images.women.dress[0],
    },
    {
        name: "Women's Coral Pattern Dress",
        gender: "women",
        type: "dress",
        price: "55.99",
        img: images.women.dress[1],
    },
    {
        name: "Women's Navy Comfort Dress",
        gender: "women",
        type: "dress",
        price: "49.69",
        img: images.women.dress[2],
    },
    {
        name: "Women's Light Pink Dress",
        gender: "women",
        type: "dress",
        price: "39.99",
        img: images.women.dress[3],
    },
    {
        name: "Women's Plant Blue Yellow Dress",
        gender: "women",
        type: "dress",
        price: "45.29",
        img: images.women.dress[4],
    },
    {
        name: "Women's Red Sequin Dess",
        gender: "women",
        type: "dress",
        price: "62.99",
        img: images.women.dress[5],
    },
    {
        name: "Women's Colorful Full Length Dress",
        gender: "women",
        type: "dress",
        price: "57.49",
        img: images.women.dress[6],
    },
    {
        name: "Women's Essential Black Dress",
        gender: "women",
        type: "dress",
        price: "24.99",
        img: images.women.dress[7],
    },
    {
        name: "Women's Short Red Dress",
        gender: "women",
        type: "dress",
        price: "34.99",
        img: images.women.dress[8],
    },
    // Womens Pants
    {
        name: "Women's Aquamarine Denim Pants",
        gender: "women",
        type: "pants",
        price: "29.99",
        img: images.women.pants[0],
    },
    {
        name: "Women's Baggy Purple Pants",
        gender: "women",
        type: "pants",
        price: "45.99",
        img: images.women.pants[1],
    },
    {
        name: "Women's Cord Jeans",
        gender: "women",
        type: "pants",
        price: "69.29",
        img: images.women.pants[2],
    },
    {
        name: "Women's Black Leggings",
        gender: "women",
        type: "pants",
        price: "19.99",
        img: images.women.pants[3],
    },
    {
        name: "Women's Green White Shorts",
        gender: "women",
        type: "pants",
        price: "14.99",
        img: images.women.pants[4],
    },
    {
        name: "Women's Ripped Jeans Shorts",
        gender: "women",
        type: "pants",
        price: "17.49",
        img: images.women.pants[5],
    },
    {
        name: "Women's Sea Pattern Leggings",
        gender: "women",
        type: "pants",
        price: "27.99",
        img: images.women.pants[6],
    },
    {
        name: "Women's Distressed Jean Shorts",
        gender: "women",
        type: "pants",
        price: "17.39",
        img: images.women.pants[7],
    },
    {
        name: "Women's Slim Fit Jean Pants",
        gender: "women",
        type: "pants",
        price: "32.99",
        img: images.women.pants[8],
    },
    // Womens Jackets
    {
        name: "Women's Denim Traditional Jacket",
        gender: "women",
        type: "jacket",
        price: "39.99",
        img: images.women.jacket[0],
    },
    {
        name: "Women's Outdoor Winter Black Jacket",
        gender: "women",
        type: "jacket",
        price: "74.49",
        img: images.women.jacket[1],
    },
    {
        name: "Women's Biker Red Zip Up Jacket",
        gender: "women",
        type: "jacket",
        price: "155.99",
        img: images.women.jacket[2],
    },
    {
        name: "Women's Button Up Formal Light Grey Jacket",
        gender: "women",
        type: "jacket",
        price: "79.99",
        img: images.women.jacket[3],
    },
    {
        name: "Women's Full Length Beige Rain Jacket",
        gender: "women",
        type: "jacket",
        price: "67.99",
        img: images.women.jacket[4],
    },
    {
        name: "Women's Leather Dark Brown Jacket",
        gender: "women",
        type: "jacket",
        price: "49.99",
        img: images.women.jacket[5],
    },
    {
        name: "Women's Button Up Formal Grey Jacket",
        gender: "women",
        type: "jacket",
        price: "82.99",
        img: images.women.jacket[6],
    },
    {
        name: "Women's Biker Neon Green Zip Up Jacket",
        gender: "women",
        type: "jacket",
        price: "164.99",
        img: images.women.jacket[7],
    },
    {
        name: "Women's PATAGONIA Outdorr Puffy Grey Jacket",
        gender: "women",
        type: "jacket",
        price: "55.99",
        img: images.women.jacket[8],
    },  
]

export default ProductList;